### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by firegreen** [Web-Imac-2017/TaleAStory#1]
Coucou
Pour faire un système de notification, j'aimerais faire en sorte qu'une requête ajax 
ne reçoive de réponse que lorsqu''il y a une mis à jour dans la base de donnée (système de notification)
Je pensais faire en sorte que le serveur dorme tant qu'il ne voit pas de mis à jour et répondent lorsqu'il voit une mise à jour (en récupérant une liste d'objet "non lu"), l'autre solution c'est de faire de l'écoute active du coté client, on fait des requêtes régulièrement pour voir s'il y a des mis à jour.
Qu'en dites vous?

**Comment by JulienRst** [comment]
En gros ce que tu peux faire : 

- Tu crées une routes notifications
- En front tu appelles cette route toutes les X secondes
- Si elle ne renvoie rien : c'est que y'a rien / si elle renvoie quelque chose c'est que y'a une notification

Moi ça me parait pas mal comme ça. 

L'écoute active ça va consommer encore plus je pense :/

Sinon vous prenez un server Node.js (c'est une blague)

**Comment by firegreen** [comment]
dacc merci
