### ISSUE TITLE
Fetch : Valeurs Post

### ISSUE THREAD

**Issue by Olyus87** [Web-Imac-2017/TaleAStory#2]
Bonjour Messieurs,
On a un ptit problème. 
En utilisant l'API fetch, on envoie des valeurs avec la méthode POST mais on ne les reçoit pas
en back. Par contre avec GET, ça fonctionne et avec un formulaire basique aussi.
On a regardé si le problème venait du htaccess mais apparemment ça ne vient pas de là.
On a regardé wamp mais normalement si ça fonctionne avec GET, ça devrait fonctionner avec POST.
On a aussi utilisé XMLHttpRequest mais c'est le même résultat.
Sauriez-vous d'où peut provenir le problème ? (jpp)

**Comment by YellowFish085** [comment]
Hello,

Question con, t'as essayé un `var_dump($_POST);` ?
Sinon, check http://stackoverflow.com/a/36669945 histoire de voir si vos envois de data en POST sont bien faits au niveau du front.

---

Autre chose, faut nous ping sinon on verra pas forcement les notifs ( via @Olyus87 )
Autre chose bis, met au moins ton morceau de code (ou mieux un lien vers les fichiers) qui posent problèmes, parce que la c'est pas évident de t'aider

**Comment by firegreen** [comment]
Salut Théo @YellowFish085,
Dsl de répondre aussi tardivement, j'avais quelques soucis avec autre choses.
On a réussi à régler le problème avec ton lien, il fallait bien faire une conversion de php://input
Merci bien :)
