### ISSUE TITLE
Changer volume

### ISSUE THREAD

**Issue by anfray-lapeyre** [Web-Imac-2017/TaleAStory#3]
Coucou,
J'essaie de faire changer le volume de plein d'objets différents à chaque frame, est-ce qu'il y a moyen de faire une référence à une valeur de volume global dans tout les objets pour régler le problème, ou est-ce qu'il faut forcément que je passe partout, et du coup que je réduise le nombre de frames où le volume est modifié ? 

(Je parle d'Audio objects javascript)

Merci d'avance,
Cordialement,
Force Blanche

**Comment by JulienRst** [comment]
@YellowFish085, une idée ?

J'avoue que j'en ai aucune idée. En théorie je dirais que c'est possible, mais ça veut dire qu'à chaque fois que tu modifies cette taille globale il faut propager l'info à tout tes objets. 

Je ne sais pas s'il vaut pas mieux passer tous les objets dans une fonction grow() ou de faire une fonction grow() qui passent tous tes objets... 

C'est une problématique intéressante en tout cas é.ê

**Comment by anfray-lapeyre** [comment]
Je ne suis pas sûr de voir ce qu'est la fonction grow() ? 
Tu parles de ça ? 
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/WebAssembly/Table/grow
Si oui je suis pas sûr de comprendre comment l'utiliser dans mon cas... 
Je pensais utiliser un dérivé de mes fonctions mute/unmute qui à peu près ce dont tu parles, mais ça reste une 30aine de calculs pour chaque frame où le volume change.
Vu que je joue déjà pas mal avec les particules, etc, j'ai peur qu'au bout d'un moment je perde les pcs les plus faibles

**Comment by JulienRst** [comment]
Non pas du tout ahah, en gros c'est une fonction que tu vas écrire toi même
et qui va augmenter la taille de tes objets ^^

Le jeu. 9 mars 2017 15:08, anfray-lapeyre <notifications@github.com> a
écrit :
